# Generated by Django 2.2.6 on 2019-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsVisitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltovisit',
            name='iterationTime',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
